[workspace]
members = [
  "playground",
  ".",
]

[package]
name = "rupl"
version = "0.0.1"
edition = "2021"

[dependencies]
rustyline-derive = "0.7.0"
lazy_static = "1.4.0"
thiserror = "1.0.39"
rustyline = "10.1.1"
termion = "2.0.1"
regex = "1.7.1"
nom = "7.1.3"
